runtime: python39
entrypoint: python3 main.py

env_variables:
  BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
  CHANNEL: '${{ secrets.CHANNEL }}'
  DEV_CHANNEL_ID: '${{ secrets.DEV_CHANNEL_ID }}'
  GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
  PLAYLIST_LINK: '${{ secrets.PLAYLIST_LINK }}'
  YOUTUBE_API_KEY: '${{ secrets.YOUTUBE_API_KEY }}'
  YOUTUBE_CHANNEL_ID: '${{ secrets.YOUTUBE_CHANNEL_ID }}'

instance_class: F2
automatic_scaling:
  max_instances: 1
