FACTION_MODIFIERS = {
    "Ardiaei": {"survivability": 1.1, "melee_strength": 2.2, "ranged_strength": 6.0},
    "Arevaci": {"survivability": 1.3, "melee_strength": 2.0, "ranged_strength": 9.0},
    "Armenia": {"survivability": 1.0, "melee_strength": 2.2, "ranged_strength": 1.7},
    "Arverni": {"survivability": 1.3, "melee_strength": 2.7, "ranged_strength": 1.0},
    "Athens": {"survivability": 1.0, "melee_strength": 2.2, "ranged_strength": 4.0},
    "Baktria": {"survivability": 1.20, "melee_strength": 2.5, "ranged_strength": 3.0},
    "Boii": {"survivability": 1.6, "melee_strength": 3.2, "ranged_strength": 2.0},
    "Carthage": {"survivability": 1.3, "melee_strength": 1.8, "ranged_strength": 7.0},
    "Cimmeria": {"survivability": 1.0, "melee_strength": 0.75, "ranged_strength": 2.7},
    "Colchis": {"survivability": 1.5, "melee_strength": 2.6, "ranged_strength": 2.0},
    "Egypt": {"survivability": 1.3, "melee_strength": 2.0, "ranged_strength": 4.5},
    "Epirus": {"survivability": 1.0, "melee_strength": 2.2, "ranged_strength": 5.0},
    "Galatia": {"survivability": 2.0, "melee_strength": 3.2, "ranged_strength": 7.0},
    "Getae": {"survivability": 1.4, "melee_strength": 2.8, "ranged_strength": 3.5},
    "Iceni": {"survivability": 1.7, "melee_strength": 2.7, "ranged_strength": 10.0},
    "Kush": {"survivability": 2.0, "melee_strength": 2.6, "ranged_strength": 1.8},
    "Lusitani": {"survivability": 1.0, "melee_strength": 2.5, "ranged_strength": 9.4},
    "Macedon": {"survivability": 1.3, "melee_strength": 1.9, "ranged_strength": 4.0},
    "Masaesyli": {"survivability": 2.0, "melee_strength": 2.0, "ranged_strength": 3.50},
    "Massilia": {"survivability": 1.1, "melee_strength": 2.0, "ranged_strength": 4.0},
    "Nabataea": {"survivability": 1.6, "melee_strength": 1.8, "ranged_strength": 5.0},
    "Nervii": {"survivability": 0.75, "melee_strength": 2.50, "ranged_strength": 1.0},
    "Odrysian Kingdom": {"survivability": 0.15, "melee_strength": 3.066, "ranged_strength": 1.0},
    "Parthia": {"survivability": 1.0, "melee_strength": 1.7, "ranged_strength": 2.1},
    "Pergamon": {"survivability": 1.2, "melee_strength": 1.0, "ranged_strength": 4.0},
    "Pontus": {"survivability": 0.85, "melee_strength": 0.75, "ranged_strength": 3.0},
    "Rome": {"survivability": 1.5, "melee_strength": 2.3, "ranged_strength": 13.0},
    "Saba": {"survivability": 1.0, "melee_strength": 2.0, "ranged_strength": 1.0},
    "Seleucid": {"survivability": 1.3, "melee_strength": 1.75, "ranged_strength": 3.3},
    "Sparta": {"survivability": 1.93, "melee_strength": 1.50, "ranged_strength": 3.7},
    "Suebi": {"survivability": 2.3, "melee_strength": 2.50, "ranged_strength": 1.7},
    "Syracuse": {"survivability": 1.0, "melee_strength": 1.7, "ranged_strength": 3.2},
    "Tylis": {"survivability": 1.7, "melee_strength": 2.8, "ranged_strength": 1.8},
}
